config/routes.rb
Rails.application.routes.draw do
  resources :locations do
    scope module: :locations do
      resources :reservations, only: [:new, :create]
    end
  end
  devise_for :owners
  devise_for :customers

  resource :booking, only: [ :show], controller: :booking
  resources :active_reservations, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :owner do
    root to: "locations#index", as: :authenticated_owner_root
  end

  authenticated :customer do
    root to: "booking#show", as: :authenticated_customer_root
  end

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :reservations, dependent: :destroy

    def within_operating_hours(reservation_date)
        reservation_time = Time.parse(reservation_date.to_s)
        reservation_time.strftime("%H%M%S") > opening_time.strftime("%H%M%S") && 
        reservation_time.strftime("%H%M%S") < closing_time.strftime("%H%M%S") 
    end
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :location
  belongs_to :customer

  delegate :email, to: :customer, prefix: true
end

app/controllers/active_reservations_controller.rb
class ActiveReservationsController < ApplicationController
    def index
        @reservations = current_customer.reservations
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
    def show
    @locations = Location.all
    end
end

app/controllers/locations/reservations_controller.rb
module Locations
    class ReservationsController < ApplicationController
        before_action :set_location

        def new
            @reservation = @location.reservations.new
        end

        def create
            @reservation = @location.reservations.new(reservation_date: params[:reservation_date])
            @reservation.customer = current_customer

            if @location.within_operating_hours(@reservation.reservation_date)
                before_date = @reservation.reservation_date - 15.minutes
                after_date = @reservation.reservation_date + 15.minutes
                if @location.reservations.where(reservation_date: before_date .. after_date).count >= @location.table_limit
                    redirect_to new_location_reservation_path(@location), alert: "Fully booked. Select another date"
                else
                    @reservation.save
                    redirect_to booking_path, notice: "You have successfully booked the restaurant"
                end

            else

                redirect_to new_location_reservation_path(@location), alert: "The time you chose is outside the operating hours"
            end

        end

        private
        def set_location
            @location = Location.find(params[:location_id])
        end
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy!

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:name, :address, :table_limit, :opening_time, :closing_time)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_reservations/_reservation.html.erb
<div class="flex flex-col items-center p-2 gap-2 bg-gray-300">
    <p>You have reservation on <%= reservation.reservation_date.strftime("%-d %B %Y, at %H:%M")%> </p>
</div>

app/views/active_reservations/index.html.erb
<div class="pt-8">
    <h1 class="flex text-3xl justify-center ">Your Active Reservations</h1>

    <div class="grid gap-2">
        <% @reservations.each do |reservation|%>
            <%= render 'reservation', reservation: reservation %>
        <% end %>
    </div>
</div>

app/views/booking/_location.html.erb
<div class="bg-gray-300 p-4 gap-4">
    <p class="text-lg">
        <%= location.name%>
    </p>

    <p class="text-lg">
        <%= location.address%>
    </p>

    <p class="text-lg">
        <%= location.table_limit%>
    </p>

    <p class="text-lg">
        Opens at <%= location.opening_time.strftime("%H:%M") %>
    </p>

    <p class="text-lg">
        Closes at <%= location.closing_time.strftime("%H:%M") %>
    </p>

    <div class="mt-4">
        <%= link_to 'Book Reservation', new_location_reservation_path(location), class:"p-2 rounded-md bg-blue-400 text-blue-50" %>
    </div>
</div>

app/views/booking/show.html.erb
<h1 class="text-4xl mt-20 px-20">Choose Hotel Location</h1>

<div class="flex p-4 justify-end">
    <%= link_to "Active reservations", active_reservations_path, class:"bg-green-500 text-green-50 p-2 rounded-lg" %>
</div>

<div class="grid md:grid-cols-4 gap-4 px-8 mt-8">
    <% @locations.each do |location|%>
        <%= render 'location', location: location %>
    <% end %>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if customer_signed_in? || owner_signed_in? %>
      <header>
        <nav class="container flex items-center bg-gray-300 py-4 px-4  ">
            <div class="py-1 px-4">
              <%= image_tag 'restaurant_logo.png', class:"w-12 h-12" %>
            </div>
            <ul class="flex flex-1 gap-12 text-page-blue items-center justify-end text-sm uppercase">
                <% if customer_signed_in? %>
                  <li><%= link_to 'Home', authenticated_customer_root_path %></li>
                <% elsif owner_signed_in? %>
                  <li><%= link_to 'Home', authenticated_owner_root_path %></li>
                <% end %>
                <%= link_to 'Sign out', destroy_customer_session_path, data: { turbo_method: :delete} %>
            </ul>
        </nav>
      </header>   
    <% end %>
    
    <%= yield %>
    
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, class: "contents") do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :table_limit %>
    <%= form.number_field :table_limit, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :opening_time %>
    <%= form.time_field :opening_time, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :closing_time %>
    <%= form.time_field :closing_time, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit "Update Restaurant", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div id="<%= dom_id location %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= location.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= location.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Table limit:</strong>
    <%= location.table_limit %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Opens at:</strong>
    <%= location.opening_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Closes at:</strong>
    <%= location.closing_time %>
  </p>

</div>

app/views/locations/_reservation.html.erb
<div class="grid gap-2 bg-gray-300">
    <p> <%= reservation.customer_email%> has booked reservation on <%= reservation.reservation_date.strftime("%-d %B %Y, at %H:%M")%> </p>
</div>

app/views/locations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing Restaurant</h1>

  <%= render "form", location: @location %>

  <%= link_to "Show restaurant info", @location, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/locations/index.html.erb
<div class="w-full p-12">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Locations" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Restaurants</h1>
    <%= link_to "New Restaurant", new_location_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="locations" class="min-w-full">
    <% @locations.each do |location| %>
      <%= render location %>
      <p>
        <%= link_to "Show this restaurant", location, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/locations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New location</h1>

  <%= render "form", location: @location %>

  <%= link_to "Back to locations", locations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/locations/reservations/new.html.erb
<div class = "flex flex-col items-center p-8">
    <h1 class="text-5xl p-8">Book a reservation at <%= @location.name%> </h1>
    
    <%= form_with url: location_reservations_path(@location) do |form|%>
        <%= form.label :reservation_date %>
        <%= form.datetime_field :reservation_date %>
        <%= form.submit "Check Date", class:"bg-green-500 text-green-50 p-2 rounded-lg"%>
    <% end %>
        
</div>

app/views/locations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @location %>
    <div class="flex flex-col gap-2">
      <% @location.reservations.each do |reservation|%>
        <%= render 'reservation', reservation: reservation %>
      <% end %>
    </div>
  

    <%= link_to "Edit restaurant info", edit_location_path(@location), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Delete", @location, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="flex flex-col items-center pt-20 bg-green-200 w-full min-h-screen">
  <h1 class="font-bold text-4xl mt-20">Restaurant Reservation App</h1>
  <p class="text-lg mt-4 ">You can easily book any restaurant of your choice.</p>

  <div class="flex gap-4 p-8 ">
    <%= link_to 'Signup as Customer', new_customer_registration_path, class:"p-2 bg-blue-400 rounded-md text-white" %>
    <%= link_to 'Signup as Owner', new_owner_registration_path, class:"p-2 bg-blue-400 rounded-md text-white" %>
  </div>

</div>